# Análise Carteira

### Utilizar o arquivo "RENDA VARIAVEL_COMPRA-VENDA.xlsx", preenchido com o histórico das compras e vendas

In [1]:
import pandas as pd
from pandas_datareader import data as pdr
import yfinance as yf
from datetime import date
import os

### Atribuindo a data de hoje em uma variavel.

### O script sempre vai considerar a data que estiver sendo rodado

In [2]:
#hoje = '2020-04-15'
hoje = date.today()
print(hoje)

2020-04-18

### Confirmar diretório e arquivo

In [3]:
arquivo_xlsx = ("RENDA VARIAVEL_COMPRA-VENDA.xlsx")

### Retorna uma lista com os nomes dos ativos(tickers), sendo os nomes das abas do arquivos

In [4]:
ativos = pd.ExcelFile(arquivo_xlsx).sheet_names
print(ativos)

['BBSE3', 'WIZS3', 'SUZB3', 'WEGE3', 'ENBR3', 'VVAR3', 'TRPL4', 'SQIA3', 'IVVB11', 'BEEF3', 'MRFG3', 'SMAL11', 'BRKM5', 'GOAU4', 'LPSB3', 'EVEN3', 'BIDI4', 'MXRF11', 'XPLG11', 'HSML11', 'KNRI11', 'XPPR11', 'BRCR11', 'BCFF11', 'XPML11', 'ITSA4', 'CVCB3', 'TAEE11', 'FLRY3', 'BOVA11']

### Salvando um arquivo txt, com a lista de todos os ativos;

In [5]:
arquivo = 'Ativos_Carteira.txt'

if os.path.isfile(arquivo):
    os.remove(arquivo)
    txt = open(arquivo, 'w')
    for i in ativos:
        txt.write(i + '\n')
    txt.close()
else:
    txt = open(arquivo, 'w')
    for i in ativos:
        txt.write(i + '\n')
    txt.close()

### Retorna uma lista, usando um loop para incluir cada aba em um dataframe, com o respectivo nome, contendo apenas uma matriz específica

In [6]:
list_df_ativos = []
for x in ativos:
    x = pd.read_excel(arquivo_xlsx, sheet_name = x, usecols= "N:O", skiprows=1, nrows=5, header=None)
    x.columns = ['VARIAVEIS', 'VALORES']
    list_df_ativos.append(x)
type(list_df_ativos)

list

### Exemplo de um elemento da lista

In [7]:
list_df_ativos[1]

          VARIAVEIS VALORES
0            TICKET   WIZS3
1              TIPO    AÇÃO
2        QUANTIDADE      50
3       PREÇO MÉDIO    9.21
4  TOTAL ATUALIZADO   460.5

### Concatenando todos os dataframes da list_df_ativos;

### Excluindo todas as colunas repetidas, no caso que tem o mesmo nome;

### Renomeando o Index;

In [8]:
df_ativos = pd.concat(list_df_ativos, axis = 1)
df_ativos = df_ativos.drop(['VARIAVEIS'], axis=1)
df_ativos = df_ativos.rename(index={0: 'TICKER', 1:'TIPO' , 2:'QUANTIDADE', 3:'PRECO_MEDIO', 4:'TOTAL_ATUALIZADO'})

In [9]:
df_ativos

,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,...,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES
TICKER,BBSE3,WIZS3,SUZB3,WEGE3,ENBR3,VVAR3,TRPL4,SQIA3,IVVB11,BEEF3,...,KNRI11,XPPR11,BRCR11,BCFF11,XPML11,ITSA4,CVCB3,TAEE11,FLRY3,BOVA11
TIPO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,ETF,AÇÃO,...,FII,FII,FII,FII,FII,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO
QUANTIDADE,10,50,0,0,10,100,8,10,0,22,...,5,2,4,11,4,100,65,20,40,0
PRECO_MEDIO,25.22,9.21,0,0,16.921,7.7671,20.2613,25.106,0,13.5041,...,178.868,119.93,121.555,92.3791,141.045,10.366,15.9152,26.165,20.272,0
TOTAL_ATUALIZADO,252.2,460.5,0,0,169.21,776.71,162.09,251.06,0,297.09,...,894.34,239.86,486.22,1016.17,564.18,1036.6,1034.49,523.3,810.88,0

### Inclui '.SA' em todos da minha carteira;
No Yahoo Finance tem '.SA' depois de todos os tickers;

In [10]:
ativos_sa = []

for i in ativos:
    sa = i + ".SA"
    ativos_sa.append(sa)
ativos_sa

['BBSE3.SA',
 'WIZS3.SA',
 'SUZB3.SA',
 'WEGE3.SA',
 'ENBR3.SA',
 'VVAR3.SA',
 'TRPL4.SA',
 'SQIA3.SA',
 'IVVB11.SA',
 'BEEF3.SA',
 'MRFG3.SA',
 'SMAL11.SA',
 'BRKM5.SA',
 'GOAU4.SA',
 'LPSB3.SA',
 'EVEN3.SA',
 'BIDI4.SA',
 'MXRF11.SA',
 'XPLG11.SA',
 'HSML11.SA',
 'KNRI11.SA',
 'XPPR11.SA',
 'BRCR11.SA',
 'BCFF11.SA',
 'XPML11.SA',
 'ITSA4.SA',
 'CVCB3.SA',
 'TAEE11.SA',
 'FLRY3.SA',
 'BOVA11.SA']

In [11]:
df_ativos.loc['TICKER'] = ativos_sa
df_ativos

,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,...,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES
TICKER,BBSE3.SA,WIZS3.SA,SUZB3.SA,WEGE3.SA,ENBR3.SA,VVAR3.SA,TRPL4.SA,SQIA3.SA,IVVB11.SA,BEEF3.SA,...,KNRI11.SA,XPPR11.SA,BRCR11.SA,BCFF11.SA,XPML11.SA,ITSA4.SA,CVCB3.SA,TAEE11.SA,FLRY3.SA,BOVA11.SA
TIPO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,ETF,AÇÃO,...,FII,FII,FII,FII,FII,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO
QUANTIDADE,10,50,0,0,10,100,8,10,0,22,...,5,2,4,11,4,100,65,20,40,0
PRECO_MEDIO,25.22,9.21,0,0,16.921,7.7671,20.2613,25.106,0,13.5041,...,178.868,119.93,121.555,92.3791,141.045,10.366,15.9152,26.165,20.272,0
TOTAL_ATUALIZADO,252.2,460.5,0,0,169.21,776.71,162.09,251.06,0,297.09,...,894.34,239.86,486.22,1016.17,564.18,1036.6,1034.49,523.3,810.88,0

### Gerando as cotações de hoje

In [12]:
#testando em apenas um ticker
teste_cotacao = pdr.get_data_yahoo('SUZB3.SA', start=hoje, end=hoje)
teste_cotacao['Close'][0]

35.84000015258789

### Gerando as cotações para toda a carteira;

In [13]:
cotacao = []

for i in ativos_sa:
    cotacao_yahoo = pdr.get_data_yahoo(i, start=hoje, end=hoje)
    cotacao_yahoo = cotacao_yahoo['Close'][0]
    cotacao.append(round(cotacao_yahoo, 3))

### Transformando a lista de cotações em um dataframe;

In [14]:
columns = []

for i in cotacao:
    columns.append('VALORES')

df_cotacao = pd.DataFrame([cotacao], index=['COTACAO'], columns=columns)
df_cotacao

,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,...,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES
COTACAO,25.92,9,35.84,38.46,16.8,6.48,19.11,18.03,162.1,9.5,...,151.38,78.25,92.85,83.7,90.23,9.14,14.67,26.78,23.72,76

### Concatenando a nova linha com as cotações no dataframe principal

In [15]:
df_ativos = pd.concat([df_ativos, df_cotacao], axis=0)
df_ativos

,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,...,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES
TICKER,BBSE3.SA,WIZS3.SA,SUZB3.SA,WEGE3.SA,ENBR3.SA,VVAR3.SA,TRPL4.SA,SQIA3.SA,IVVB11.SA,BEEF3.SA,...,KNRI11.SA,XPPR11.SA,BRCR11.SA,BCFF11.SA,XPML11.SA,ITSA4.SA,CVCB3.SA,TAEE11.SA,FLRY3.SA,BOVA11.SA
TIPO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,ETF,AÇÃO,...,FII,FII,FII,FII,FII,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO
QUANTIDADE,10,50,0,0,10,100,8,10,0,22,...,5,2,4,11,4,100,65,20,40,0
PRECO_MEDIO,25.22,9.21,0,0,16.921,7.7671,20.2613,25.106,0,13.5041,...,178.868,119.93,121.555,92.3791,141.045,10.366,15.9152,26.165,20.272,0
TOTAL_ATUALIZADO,252.2,460.5,0,0,169.21,776.71,162.09,251.06,0,297.09,...,894.34,239.86,486.22,1016.17,564.18,1036.6,1034.49,523.3,810.88,0
COTACAO,25.92,9,35.84,38.46,16.8,6.48,19.11,18.03,162.1,9.5,...,151.38,78.25,92.85,83.7,90.23,9.14,14.67,26.78,23.72,76

### Incluindo linha com lucro ou prejuízo

In [16]:
lucro_prejuizo = []

for i in range(len(df_ativos.iloc[1])):
    preço = df_ativos.iloc[4,i]
    quantidade = df_ativos.iloc[2,i]
    cotacao = df_ativos.iloc[5,i]
    valor_atualizado = (quantidade*cotacao)-preço
    lucro_prejuizo.append(valor_atualizado)

### Transformando a lista de cotações em um dataframe;

### Concatenando a nova linha com as cotações no dataframe principal;

In [17]:
columns = []

for i in lucro_prejuizo:
    columns.append('VALORES')

df_cotacao = pd.DataFrame([lucro_prejuizo], index=['LUCRO_PREJUIZO'], columns=columns)
df_cotacao

df_ativos = pd.concat([df_ativos, df_cotacao], axis=0)
df_ativos

,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,...,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES,VALORES
TICKER,BBSE3.SA,WIZS3.SA,SUZB3.SA,WEGE3.SA,ENBR3.SA,VVAR3.SA,TRPL4.SA,SQIA3.SA,IVVB11.SA,BEEF3.SA,...,KNRI11.SA,XPPR11.SA,BRCR11.SA,BCFF11.SA,XPML11.SA,ITSA4.SA,CVCB3.SA,TAEE11.SA,FLRY3.SA,BOVA11.SA
TIPO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,ETF,AÇÃO,...,FII,FII,FII,FII,FII,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO
QUANTIDADE,10,50,0,0,10,100,8,10,0,22,...,5,2,4,11,4,100,65,20,40,0
PRECO_MEDIO,25.22,9.21,0,0,16.921,7.7671,20.2613,25.106,0,13.5041,...,178.868,119.93,121.555,92.3791,141.045,10.366,15.9152,26.165,20.272,0
TOTAL_ATUALIZADO,252.2,460.5,0,0,169.21,776.71,162.09,251.06,0,297.09,...,894.34,239.86,486.22,1016.17,564.18,1036.6,1034.49,523.3,810.88,0
COTACAO,25.92,9,35.84,38.46,16.8,6.48,19.11,18.03,162.1,9.5,...,151.38,78.25,92.85,83.7,90.23,9.14,14.67,26.78,23.72,76
PROFIT_LOSS,7,-10.5,0,0,-1.21,-128.71,-9.21,-70.76,0,-88.09,...,-137.44,-83.36,-114.82,-95.47,-203.26,-122.6,-80.94,12.3,137.92,0

### Renomeando os lables das colunas, colocando o respectivo nome do papel;

### Excluindo a linha "TICKER";

In [18]:
df_ativos.set_axis(ativos, axis=1, inplace=True)
df_ativos.drop(['TICKER'], inplace=True)
df_ativos

,BBSE3,WIZS3,SUZB3,WEGE3,ENBR3,VVAR3,TRPL4,SQIA3,IVVB11,BEEF3,...,KNRI11,XPPR11,BRCR11,BCFF11,XPML11,ITSA4,CVCB3,TAEE11,FLRY3,BOVA11
TIPO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,ETF,AÇÃO,...,FII,FII,FII,FII,FII,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO
QUANTIDADE,10,50,0,0,10,100,8,10,0,22,...,5,2,4,11,4,100,65,20,40,0
PRECO_MEDIO,25.22,9.21,0,0,16.921,7.7671,20.2613,25.106,0,13.5041,...,178.868,119.93,121.555,92.3791,141.045,10.366,15.9152,26.165,20.272,0
TOTAL_ATUALIZADO,252.2,460.5,0,0,169.21,776.71,162.09,251.06,0,297.09,...,894.34,239.86,486.22,1016.17,564.18,1036.6,1034.49,523.3,810.88,0
COTACAO,25.92,9,35.84,38.46,16.8,6.48,19.11,18.03,162.1,9.5,...,151.38,78.25,92.85,83.7,90.23,9.14,14.67,26.78,23.72,76
PROFIT_LOSS,7,-10.5,0,0,-1.21,-128.71,-9.21,-70.76,0,-88.09,...,-137.44,-83.36,-114.82,-95.47,-203.26,-122.6,-80.94,12.3,137.92,0

### Incluindo linha com o Lucro/Prejuízo Percentual

In [19]:
columns = []
lucro_prejuizo_percent = []

for i in range(len(df_ativos.iloc[0])):
    ticker = ativos[i]
    columns.append(ticker)
    if df_ativos.iloc[3,i] == 0:
        lucro_prejuizo_percent.append("0%")
    else:
        total_atualizado = df_ativos.iloc[3,i]
        lucro_prejuizo = df_ativos.iloc[5,i]
        total_lucro_prejuizo = round((lucro_prejuizo/total_atualizado*100),2)
        lucro_prejuizo_percent.append(str(total_lucro_prejuizo) + "%")
    
df_lucro_prejuizo_percent = pd.DataFrame([lucro_prejuizo_percent], index=['LUCRO_PREJUIZO (VARIACAO %)'], columns=columns)
df_lucro_prejuizo_percent

df_ativos = pd.concat([df_ativos, df_lucro_prejuizo_percent], axis=0)
df_ativos

,BBSE3,WIZS3,SUZB3,WEGE3,ENBR3,VVAR3,TRPL4,SQIA3,IVVB11,BEEF3,...,KNRI11,XPPR11,BRCR11,BCFF11,XPML11,ITSA4,CVCB3,TAEE11,FLRY3,BOVA11
TIPO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,ETF,AÇÃO,...,FII,FII,FII,FII,FII,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO
QUANTIDADE,10,50,0,0,10,100,8,10,0,22,...,5,2,4,11,4,100,65,20,40,0
PRECO_MEDIO,25.22,9.21,0,0,16.921,7.7671,20.2613,25.106,0,13.5041,...,178.868,119.93,121.555,92.3791,141.045,10.366,15.9152,26.165,20.272,0
TOTAL_ATUALIZADO,252.2,460.5,0,0,169.21,776.71,162.09,251.06,0,297.09,...,894.34,239.86,486.22,1016.17,564.18,1036.6,1034.49,523.3,810.88,0
COTACAO,25.92,9,35.84,38.46,16.8,6.48,19.11,18.03,162.1,9.5,...,151.38,78.25,92.85,83.7,90.23,9.14,14.67,26.78,23.72,76
PROFIT_LOSS,7,-10.5,0,0,-1.21,-128.71,-9.21,-70.76,0,-88.09,...,-137.44,-83.36,-114.82,-95.47,-203.26,-122.6,-80.94,12.3,137.92,0
LUCRO_PREJUIZO (VARIACAO %),2.78%,-2.28%,0%,0%,-0.72%,-16.57%,-5.68%,-28.18%,0%,-29.65%,...,-15.37%,-34.75%,-23.61%,-9.4%,-36.03%,-11.83%,-7.82%,2.35%,17.01%,0%

### Importando e Incluindo os Proventos Recebidos;

In [20]:
arquivo_xlsx = ("RENDA VARIAVEL_DIVIDENDOS-PROVENTOS.xlsx")

df_proventos = pd.read_excel(arquivo_xlsx, usecols= [1,3])
df_proventos.dropna(inplace=True)
df_proventos = df_proventos.groupby(['TICKET'], as_index=False).sum()

df_proventos_0 = pd.DataFrame(ativos)
df_proventos_0["TOTAL"] = float(0)
df_proventos_0.rename(columns={0:'TICKET'}, inplace=True)

df_proventos = pd.concat([df_proventos_0, df_proventos])
df_proventos = df_proventos.groupby(['TICKET'], as_index=False, sort=False).sum()

columns = []
prov = []

for i in range(len(df_proventos)):
    ticker = df_proventos.iloc[i][0]
    columns.append(ticker)
    valor = round(df_proventos.iloc[i][1],2)
    prov.append(valor)
df_proventos = pd.DataFrame([prov], index=['PROVENTOS'], columns=columns)
df_proventos

df_ativos = pd.concat([df_ativos, df_proventos], axis=0)
df_ativos

,BBSE3,WIZS3,SUZB3,WEGE3,ENBR3,VVAR3,TRPL4,SQIA3,IVVB11,BEEF3,...,KNRI11,XPPR11,BRCR11,BCFF11,XPML11,ITSA4,CVCB3,TAEE11,FLRY3,BOVA11
TIPO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,ETF,AÇÃO,...,FII,FII,FII,FII,FII,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO
QUANTIDADE,10,50,0,0,10,100,8,10,0,22,...,5,2,4,11,4,100,65,20,40,0
PRECO_MEDIO,25.22,9.21,0,0,16.921,7.7671,20.2613,25.106,0,13.5041,...,178.868,119.93,121.555,92.3791,141.045,10.366,15.9152,26.165,20.272,0
TOTAL_ATUALIZADO,252.2,460.5,0,0,169.21,776.71,162.09,251.06,0,297.09,...,894.34,239.86,486.22,1016.17,564.18,1036.6,1034.49,523.3,810.88,0
COTACAO,25.92,9,35.84,38.46,16.8,6.48,19.11,18.03,162.1,9.5,...,151.38,78.25,92.85,83.7,90.23,9.14,14.67,26.78,23.72,76
PROFIT_LOSS,7,-10.5,0,0,-1.21,-128.71,-9.21,-70.76,0,-88.09,...,-137.44,-83.36,-114.82,-95.47,-203.26,-122.6,-80.94,12.3,137.92,0
LUCRO_PREJUIZO (VARIACAO %),2.78%,-2.28%,0%,0%,-0.72%,-16.57%,-5.68%,-28.18%,0%,-29.65%,...,-15.37%,-34.75%,-23.61%,-9.4%,-36.03%,-11.83%,-7.82%,2.35%,17.01%,0%
PROVENTOS,0,0,0,1.17,0,0,0,0,0,0,...,7.4,2.08,5.73,8.35,4.44,10.27,0,0,0,0

### Incluindo linha com o Dividend Yield
Considerando valor médio para 12 meses (Proventos/12);

In [21]:
dividend_yield = []
columns = []
dividend_yield_percent = []

for i in range(len(df_ativos.iloc[1])):
    proventos = int(df_ativos.iloc[7,i])
    quantidade = df_ativos.iloc[1,i]
    if quantidade == 0:
        dividend_yield_ano = 0
        dividend_yield.append(str(dividend_yield_ano)+"%")
        columns.append(ativos[i])
        dividend_yield_percent.append(float(dividend_yield_mes*100))
    else:
        proventos_per_acao = (proventos/quantidade)
        cotacao = df_ativos.iloc[4,i]
        dividend_yield_bruto = (proventos_per_acao/cotacao)
        dividend_yield_mes = dividend_yield_bruto/int(date.today().strftime('%m'))
        dividend_yield_ano = round((dividend_yield_mes*12)*100,2)
        dividend_yield.append(str(dividend_yield_ano)+"%")
        columns.append(ativos[i])
        dividend_yield_percent.append(float(dividend_yield_mes*100))  
        
df_dividend_yield = pd.DataFrame([dividend_yield], index=['DIVIDEND_YIELD (MÉDIA 12 MESES)'], columns=columns)
df_dividend_yield

df_ativos = pd.concat([df_ativos, df_dividend_yield], axis=0)
df_ativos

,BBSE3,WIZS3,SUZB3,WEGE3,ENBR3,VVAR3,TRPL4,SQIA3,IVVB11,BEEF3,...,KNRI11,XPPR11,BRCR11,BCFF11,XPML11,ITSA4,CVCB3,TAEE11,FLRY3,BOVA11
TIPO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,ETF,AÇÃO,...,FII,FII,FII,FII,FII,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO
QUANTIDADE,10,50,0,0,10,100,8,10,0,22,...,5,2,4,11,4,100,65,20,40,0
PRECO_MEDIO,25.22,9.21,0,0,16.921,7.7671,20.2613,25.106,0,13.5041,...,178.868,119.93,121.555,92.3791,141.045,10.366,15.9152,26.165,20.272,0
TOTAL_ATUALIZADO,252.2,460.5,0,0,169.21,776.71,162.09,251.06,0,297.09,...,894.34,239.86,486.22,1016.17,564.18,1036.6,1034.49,523.3,810.88,0
COTACAO,25.92,9,35.84,38.46,16.8,6.48,19.11,18.03,162.1,9.5,...,151.38,78.25,92.85,83.7,90.23,9.14,14.67,26.78,23.72,76
PROFIT_LOSS,7,-10.5,0,0,-1.21,-128.71,-9.21,-70.76,0,-88.09,...,-137.44,-83.36,-114.82,-95.47,-203.26,-122.6,-80.94,12.3,137.92,0
LUCRO_PREJUIZO (VARIACAO %),2.78%,-2.28%,0%,0%,-0.72%,-16.57%,-5.68%,-28.18%,0%,-29.65%,...,-15.37%,-34.75%,-23.61%,-9.4%,-36.03%,-11.83%,-7.82%,2.35%,17.01%,0%
PROVENTOS,0,0,0,1.17,0,0,0,0,0,0,...,7.4,2.08,5.73,8.35,4.44,10.27,0,0,0,0
DIVIDEND_YIELD (MÉDIA 12 MESES),0.0%,0.0%,0%,0%,0.0%,0.0%,0.0%,0.0%,0%,0.0%,...,2.77%,3.83%,4.04%,2.61%,3.32%,3.28%,0.0%,0.0%,0.0%,0%

### Incluindo linha com o Yield On Cost
Considerando valor médio para 12 meses (Preço Médio);

In [22]:
columns = []
yield_on_cost_percent = []

for i in range(len(df_ativos.iloc[1])):
    proventos = int(df_ativos.iloc[7,i])
    quantidade = df_ativos.iloc[1,i]
    if quantidade == 0:
        dividend_yield_ano = 0
        dividend_yield.append(str(dividend_yield_ano)+"%")
        columns.append(ativos[i])
        yield_on_cost_percent.append(float(dividend_yield_mes*100))
    else:
        proventos_per_acao = (proventos/quantidade)
        preco_medio = df_ativos.iloc[2,i]
        yield_on_cost_bruto = (proventos_per_acao/preco_medio)
        yield_on_cost_mes = yield_on_cost_bruto/int(date.today().strftime('%m'))
        yield_on_cost_ano = round((yield_on_cost_mes*12)*100,2)
        yield_on_cost_percent.append(str(yield_on_cost_ano)+"%")
        columns.append(ativos[i])
        
df_yield_on_cost = pd.DataFrame([yield_on_cost_percent], index=['YIELD_ON_COST (MÉDIA 12 MESES)'], columns=columns)
df_yield_on_cost

df_ativos = pd.concat([df_ativos, df_yield_on_cost], axis=0)
df_ativos

,BBSE3,WIZS3,SUZB3,WEGE3,ENBR3,VVAR3,TRPL4,SQIA3,IVVB11,BEEF3,...,KNRI11,XPPR11,BRCR11,BCFF11,XPML11,ITSA4,CVCB3,TAEE11,FLRY3,BOVA11
TIPO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO,ETF,AÇÃO,...,FII,FII,FII,FII,FII,AÇÃO,AÇÃO,AÇÃO,AÇÃO,AÇÃO
QUANTIDADE,10,50,0,0,10,100,8,10,0,22,...,5,2,4,11,4,100,65,20,40,0
PRECO_MEDIO,25.22,9.21,0,0,16.921,7.7671,20.2613,25.106,0,13.5041,...,178.868,119.93,121.555,92.3791,141.045,10.366,15.9152,26.165,20.272,0
TOTAL_ATUALIZADO,252.2,460.5,0,0,169.21,776.71,162.09,251.06,0,297.09,...,894.34,239.86,486.22,1016.17,564.18,1036.6,1034.49,523.3,810.88,0
COTACAO,25.92,9,35.84,38.46,16.8,6.48,19.11,18.03,162.1,9.5,...,151.38,78.25,92.85,83.7,90.23,9.14,14.67,26.78,23.72,76
PROFIT_LOSS,7,-10.5,0,0,-1.21,-128.71,-9.21,-70.76,0,-88.09,...,-137.44,-83.36,-114.82,-95.47,-203.26,-122.6,-80.94,12.3,137.92,0
LUCRO_PREJUIZO (VARIACAO %),2.78%,-2.28%,0%,0%,-0.72%,-16.57%,-5.68%,-28.18%,0%,-29.65%,...,-15.37%,-34.75%,-23.61%,-9.4%,-36.03%,-11.83%,-7.82%,2.35%,17.01%,0%
PROVENTOS,0,0,0,1.17,0,0,0,0,0,0,...,7.4,2.08,5.73,8.35,4.44,10.27,0,0,0,0
DIVIDEND_YIELD (MÉDIA 12 MESES),0.0%,0.0%,0%,0%,0.0%,0.0%,0.0%,0.0%,0%,0.0%,...,2.77%,3.83%,4.04%,2.61%,3.32%,3.28%,0.0%,0.0%,0.0%,0%
YIELD_ON_COST (MÉDIA 12 MESES),0.0%,0.0%,0,0,0.0%,0.0%,0.0%,0.0%,0,0.0%,...,2.35%,2.5%,3.09%,2.36%,2.13%,2.89%,0.0%,0.0%,0.0%,0

### Totalizando os proventos, valor investido e lucro/prejuízo pelo "Tipo";

In [23]:
fii_total = []
fii_prov = []
fii_lucro_prejuizo = []
acao_total = []
acao_prov = []
acao_lucro_prejuizo = []
etf = []
etf_lucro_prejuizo = []

for i in range(len(df_ativos.iloc[1])):
    if df_ativos.iloc[0,i] == 'AÇÃO':
        acao_total.append(df_ativos.iloc[3,i])
        acao_prov.append(df_ativos.iloc[7,i])
        acao_lucro_prejuizo.append(df_ativos.iloc[5,i])
    elif df_ativos.iloc[0,i] == 'FII':
        fii_total.append(df_ativos.iloc[3,i])
        fii_prov.append(df_ativos.iloc[7,i])
        fii_lucro_prejuizo.append(df_ativos.iloc[5,i])        
    else:
        etf.append(df_ativos.iloc[3,i])
        etf_lucro_prejuizo.append(df_ativos.iloc[5,i])

### Gerando um novo Arquivo.csv;

In [24]:
arquivo = 'Analise_Carteira.csv'

if os.path.isfile(arquivo):
    os.remove(arquivo)
    df_ativos.to_csv('Analise_Carteira.csv', encoding='latin-1')
else:
    df_ativos.to_csv('Analise_Carteira.csv', encoding='latin-1')

### Gerando algumas informações gerais resumidas;

In [53]:
print('            Quantidade X Total Investido            \n')

total_investido = sum(acao_total) + sum(fii_total) + sum(etf)

contador_quantidade = []
for i in range(len(df_ativos.iloc[1])):
    contador_quantidade.append(0) if df_ativos.iloc[1,i] == 0 else contador_quantidade.append(1)
quantidade = sum(contador_quantidade)

acao_total_percent = (sum(acao_total)/total_investido)*100
fii_total_percent = (sum(fii_total)/total_investido)*100
etf_total_percent = (sum(etf)/total_investido)*100

print("Quantidade de Ativos: {}".format(quantidade))
print("Total Investido: R$ {} (100%)".format(round((total_investido),2)))
print('Ações Total: R$ {} ({}%)'.format(sum(acao_total), round(acao_total_percent,2)))
print('FII Total: R$ {} ({}%)'.format(sum(fii_total), round(fii_total_percent,2)))
print('ETF Total: R$ {} ({}%)'.format(round(sum(etf),2), round(etf_total_percent,2)))
print('____________________________________________________\n')

print('                Lucro/Prejuízo Total                \n')

total_lucro_prejuizo = sum(acao_lucro_prejuizo) + sum(fii_lucro_prejuizo) + sum(etf_lucro_prejuizo)
total_lucro_prejuizo_percentual = (total_lucro_prejuizo/total_investido)*100
acao_lucro_prejuizo_percent = (sum(acao_lucro_prejuizo)/total_lucro_prejuizo)*100
fii_lucro_prejuizo_percent = (sum(fii_lucro_prejuizo)/total_lucro_prejuizo)*100
etf_lucro_prejuizo_percent = (sum(etf_lucro_prejuizo)/total_lucro_prejuizo)*100

print("Total Lucro/Prejuízo: R$ {} (100%)".format(round((total_lucro_prejuizo),2)))
print('Ações Total: R$ {} ({}%)'.format(round(sum(acao_lucro_prejuizo),2), round(acao_lucro_prejuizo_percent,2)))
print('FII Total: R$ {} ({}%)'.format(round(sum(fii_lucro_prejuizo),2), round(fii_lucro_prejuizo_percent,2)))
print('ETF Total: R$ {} ({}%)'.format(round(sum(etf_lucro_prejuizo),2), round(etf_lucro_prejuizo_percent,2)))
print("Percentual Lucro/Prejuízo Total: {}%".format(round((total_lucro_prejuizo_percentual),2)))
print("Total Investido Atualizado: R$ {}".format(round(total_investido + total_lucro_prejuizo),2))
print("____________________________________________________\n")
      
print('     Total Proventos Recebidos X Dividend Yield     \n')
      
dividend_yield_total = sum(acao_prov) + sum(fii_prov)
dividend_yield_percent_mes = sum(dividend_yield_percent)/quantidade #total recebido / quantidade ativos
acao_prov_percent = (sum(acao_prov)/dividend_yield_total)*100
fii_prov_percent = (sum(fii_prov)/dividend_yield_total)*100

print('Total Proventos Recebidos: R$ {} (100%)'.format(round(dividend_yield_total),2))
print('Ações Total: R$ {} ({}%)'.format(round(sum(acao_prov),2), round(acao_prov_percent,2)))
print('FII Total: R$ {} ({}%)'.format(round(sum(fii_prov),2), round(fii_prov_percent,2)))
print('Dividend Yield Mensal: {}%'.format(round(dividend_yield_percent_mes, 3))) #considerando os meus recebimentos em 2020/meses
print('Dividend Yield: {}%'.format(round(dividend_yield_percent_mes*12, 2))) #considerando os meus recebimentos mes * 12

            Quantidade X Total Investido

Quantidade de Ativos: 25
Total Investido: R$ 15525.65 (100%)
Ações Total: R$ 9982.75 (64.3%)
FII Total: R$ 5124.46 (33.01%)
ETF Total: R$ 418.44 (2.7%)
____________________________________________________

                Lucro/Prejuízo Total

Total Lucro/Prejuízo: R$ -2577.75 (100%)
Ações Total: R$ -1389.62 (53.91%)
FII Total: R$ -1030.69 (39.98%)
ETF Total: R$ -157.44 (6.11%)
Percentual Lucro/Prejuízo Total: -16.6%
Total Investido Atualizado: R$ 12948
____________________________________________________

     Total Proventos Recebidos X Dividend Yield

Total Proventos Recebidos: R$ 55 (100%)
Ações Total: R$ 12.9 (23.45%)
FII Total: R$ 42.1 (76.55%)
Dividend Yield Mensal: 0.096%
Dividend Yield: 1.15%

### Input para resumir um ativo específico

In [46]:
print('Consultando um ativo\n')

print(ativos, '\n')
codigo = input('Digite um Código da Lista: ')

df_ativos.loc[:,codigo]

Consultando um ativo

['BBSE3', 'WIZS3', 'SUZB3', 'WEGE3', 'ENBR3', 'VVAR3', 'TRPL4', 'SQIA3', 'IVVB11', 'BEEF3', 'MRFG3', 'SMAL11', 'BRKM5', 'GOAU4', 'LPSB3', 'EVEN3', 'BIDI4', 'MXRF11', 'XPLG11', 'HSML11', 'KNRI11', 'XPPR11', 'BRCR11', 'BCFF11', 'XPML11', 'ITSA4', 'CVCB3', 'TAEE11', 'FLRY3', 'BOVA11']

Digite um Código da Lista: SMAL11

TIPO                                   ETF
QUANTIDADE                               3
PRECO_MEDIO                         139.48
TOTAL_ATUALIZADO                    418.44
COTACAO                                 87
PROFIT_LOSS                        -157.44
LUCRO_PREJUIZO (VARIACAO %)        -37.63%
PROVENTOS                                0
DIVIDEND_YIELD (MÉDIA 12 MESES)       0.0%
YIELD_ON_COST (MÉDIA 12 MESES)        0.0%
Name: SMAL11, dtype: object